# Generated by Django 5.2.5 on 2025-08-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_customer",
            field=models.BooleanField(default=True),
        ),
    ]
